# Generated by Django 4.2.7 on 2024-01-12 09:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Images/')),
                ('video', models.FileField(blank=True, upload_to='Videos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(to='blog.author')),
            ],
        ),
    ]
